/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_emmef_sndfile_SoundFile */

#ifndef _Included_org_emmef_sndfile_SoundFile
#define _Included_org_emmef_sndfile_SoundFile
#ifdef __cplusplus
extern "C" {
#endif
#undef org_emmef_sndfile_SoundFile_WHENCE_SET
#define org_emmef_sndfile_SoundFile_WHENCE_SET 1L
#undef org_emmef_sndfile_SoundFile_WHENCE_CURRENT
#define org_emmef_sndfile_SoundFile_WHENCE_CURRENT 2L
#undef org_emmef_sndfile_SoundFile_WHENCE_FROM_END
#define org_emmef_sndfile_SoundFile_WHENCE_FROM_END 3L
/*
 * Class:     org_emmef_sndfile_SoundFile
 * Method:    openWriteable
 * Signature: (Ljava/lang/String;Lorg/emmef/sndfile/Info;)J
 */
JNIEXPORT jlong JNICALL Java_org_emmef_sndfile_SoundFile_openWriteable
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     org_emmef_sndfile_SoundFile
 * Method:    openReadable
 * Signature: (Ljava/lang/String;Lorg/emmef/sndfile/Info;)J
 */
JNIEXPORT jlong JNICALL Java_org_emmef_sndfile_SoundFile_openReadable
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     org_emmef_sndfile_SoundFile
 * Method:    closeHandle
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_emmef_sndfile_SoundFile_closeHandle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_emmef_sndfile_SoundFile
 * Method:    readDouble
 * Signature: (J[DIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_emmef_sndfile_SoundFile_readDouble
  (JNIEnv *, jclass, jlong, jdoubleArray, jint, jlong);

/*
 * Class:     org_emmef_sndfile_SoundFile
 * Method:    readFloat
 * Signature: (J[FIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_emmef_sndfile_SoundFile_readFloat
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jlong);

/*
 * Class:     org_emmef_sndfile_SoundFile
 * Method:    readInteger
 * Signature: (J[IIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_emmef_sndfile_SoundFile_readInteger
  (JNIEnv *, jclass, jlong, jintArray, jint, jlong);

/*
 * Class:     org_emmef_sndfile_SoundFile
 * Method:    readShort
 * Signature: (J[SIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_emmef_sndfile_SoundFile_readShort
  (JNIEnv *, jclass, jlong, jshortArray, jint, jlong);

/*
 * Class:     org_emmef_sndfile_SoundFile
 * Method:    writeDouble
 * Signature: (J[DIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_emmef_sndfile_SoundFile_writeDouble
  (JNIEnv *, jclass, jlong, jdoubleArray, jint, jlong);

/*
 * Class:     org_emmef_sndfile_SoundFile
 * Method:    writeFloat
 * Signature: (J[FIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_emmef_sndfile_SoundFile_writeFloat
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jlong);

/*
 * Class:     org_emmef_sndfile_SoundFile
 * Method:    writeInteger
 * Signature: (J[IIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_emmef_sndfile_SoundFile_writeInteger
  (JNIEnv *, jclass, jlong, jintArray, jint, jlong);

/*
 * Class:     org_emmef_sndfile_SoundFile
 * Method:    writeShort
 * Signature: (J[SIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_emmef_sndfile_SoundFile_writeShort
  (JNIEnv *, jclass, jlong, jshortArray, jint, jlong);

/*
 * Class:     org_emmef_sndfile_SoundFile
 * Method:    seek
 * Signature: (JJLorg/emmef/sndfile/SoundFile/Whence;)J
 */
JNIEXPORT jlong JNICALL Java_org_emmef_sndfile_SoundFile_seek
  (JNIEnv *, jclass, jlong, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_emmef_sndfile_SoundFile_Mode */

#ifndef _Included_org_emmef_sndfile_SoundFile_Mode
#define _Included_org_emmef_sndfile_SoundFile_Mode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_emmef_sndfile_SoundFile_Whence */

#ifndef _Included_org_emmef_sndfile_SoundFile_Whence
#define _Included_org_emmef_sndfile_SoundFile_Whence
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_emmef_sndfile_SoundFileType */

#ifndef _Included_org_emmef_sndfile_SoundFileType
#define _Included_org_emmef_sndfile_SoundFileType
#ifdef __cplusplus
extern "C" {
#endif
#undef org_emmef_sndfile_SoundFileType_MASK_SUBTYPE
#define org_emmef_sndfile_SoundFileType_MASK_SUBTYPE 65535L
#undef org_emmef_sndfile_SoundFileType_MASK_TYPE
#define org_emmef_sndfile_SoundFileType_MASK_TYPE 268369920L
#undef org_emmef_sndfile_SoundFileType_MASK_ENDIAN
#define org_emmef_sndfile_SoundFileType_MASK_ENDIAN 805306368L
#undef org_emmef_sndfile_SoundFileType_TYPE_WAV
#define org_emmef_sndfile_SoundFileType_TYPE_WAV 65536L
#undef org_emmef_sndfile_SoundFileType_TYPE_AIFF
#define org_emmef_sndfile_SoundFileType_TYPE_AIFF 131072L
#undef org_emmef_sndfile_SoundFileType_TYPE_AU
#define org_emmef_sndfile_SoundFileType_TYPE_AU 196608L
#undef org_emmef_sndfile_SoundFileType_TYPE_RAW
#define org_emmef_sndfile_SoundFileType_TYPE_RAW 262144L
#undef org_emmef_sndfile_SoundFileType_TYPE_PAF
#define org_emmef_sndfile_SoundFileType_TYPE_PAF 327680L
#undef org_emmef_sndfile_SoundFileType_TYPE_SVX
#define org_emmef_sndfile_SoundFileType_TYPE_SVX 393216L
#undef org_emmef_sndfile_SoundFileType_TYPE_NIST
#define org_emmef_sndfile_SoundFileType_TYPE_NIST 458752L
#undef org_emmef_sndfile_SoundFileType_TYPE_VOC
#define org_emmef_sndfile_SoundFileType_TYPE_VOC 524288L
#undef org_emmef_sndfile_SoundFileType_TYPE_IRCAM
#define org_emmef_sndfile_SoundFileType_TYPE_IRCAM 655360L
#undef org_emmef_sndfile_SoundFileType_TYPE_W64
#define org_emmef_sndfile_SoundFileType_TYPE_W64 720896L
#undef org_emmef_sndfile_SoundFileType_TYPE_MAT4
#define org_emmef_sndfile_SoundFileType_TYPE_MAT4 786432L
#undef org_emmef_sndfile_SoundFileType_TYPE_MAT5
#define org_emmef_sndfile_SoundFileType_TYPE_MAT5 851968L
#undef org_emmef_sndfile_SoundFileType_FORMAT_PCM_S8
#define org_emmef_sndfile_SoundFileType_FORMAT_PCM_S8 1L
#undef org_emmef_sndfile_SoundFileType_FORMAT_PCM_16
#define org_emmef_sndfile_SoundFileType_FORMAT_PCM_16 2L
#undef org_emmef_sndfile_SoundFileType_FORMAT_PCM_24
#define org_emmef_sndfile_SoundFileType_FORMAT_PCM_24 3L
#undef org_emmef_sndfile_SoundFileType_FORMAT_PCM_32
#define org_emmef_sndfile_SoundFileType_FORMAT_PCM_32 4L
#undef org_emmef_sndfile_SoundFileType_FORMAT_PCM_U8
#define org_emmef_sndfile_SoundFileType_FORMAT_PCM_U8 5L
#undef org_emmef_sndfile_SoundFileType_FORMAT_FLOAT
#define org_emmef_sndfile_SoundFileType_FORMAT_FLOAT 6L
#undef org_emmef_sndfile_SoundFileType_FORMAT_DOUBLE
#define org_emmef_sndfile_SoundFileType_FORMAT_DOUBLE 7L
#undef org_emmef_sndfile_SoundFileType_FORMAT_ULAW
#define org_emmef_sndfile_SoundFileType_FORMAT_ULAW 16L
#undef org_emmef_sndfile_SoundFileType_FORMAT_ALAW
#define org_emmef_sndfile_SoundFileType_FORMAT_ALAW 17L
#undef org_emmef_sndfile_SoundFileType_FORMAT_IMA_ADPCM
#define org_emmef_sndfile_SoundFileType_FORMAT_IMA_ADPCM 18L
#undef org_emmef_sndfile_SoundFileType_FORMAT_MS_ADPCM
#define org_emmef_sndfile_SoundFileType_FORMAT_MS_ADPCM 19L
#undef org_emmef_sndfile_SoundFileType_FORMAT_GSM610
#define org_emmef_sndfile_SoundFileType_FORMAT_GSM610 32L
#undef org_emmef_sndfile_SoundFileType_FORMAT_VOX_ADPCM
#define org_emmef_sndfile_SoundFileType_FORMAT_VOX_ADPCM 33L
#undef org_emmef_sndfile_SoundFileType_FORMAT_G721_32
#define org_emmef_sndfile_SoundFileType_FORMAT_G721_32 48L
#undef org_emmef_sndfile_SoundFileType_FORMAT_G723_24
#define org_emmef_sndfile_SoundFileType_FORMAT_G723_24 49L
#undef org_emmef_sndfile_SoundFileType_FORMAT_G723_40
#define org_emmef_sndfile_SoundFileType_FORMAT_G723_40 50L
#undef org_emmef_sndfile_SoundFileType_FORMAT_DWVW_12
#define org_emmef_sndfile_SoundFileType_FORMAT_DWVW_12 64L
#undef org_emmef_sndfile_SoundFileType_FORMAT_DWVW_16
#define org_emmef_sndfile_SoundFileType_FORMAT_DWVW_16 65L
#undef org_emmef_sndfile_SoundFileType_FORMAT_DWVW_24
#define org_emmef_sndfile_SoundFileType_FORMAT_DWVW_24 66L
#undef org_emmef_sndfile_SoundFileType_FORMAT_DWVW_N
#define org_emmef_sndfile_SoundFileType_FORMAT_DWVW_N 67L
#undef org_emmef_sndfile_SoundFileType_ENDIAN_FILE
#define org_emmef_sndfile_SoundFileType_ENDIAN_FILE 0L
#undef org_emmef_sndfile_SoundFileType_ENDIAN_LITTLE
#define org_emmef_sndfile_SoundFileType_ENDIAN_LITTLE 268435456L
#undef org_emmef_sndfile_SoundFileType_ENDIAN_BIG
#define org_emmef_sndfile_SoundFileType_ENDIAN_BIG 536870912L
#undef org_emmef_sndfile_SoundFileType_ENDIAN_CPU
#define org_emmef_sndfile_SoundFileType_ENDIAN_CPU 805306368L
/*
 * Class:     org_emmef_sndfile_SoundFileType
 * Method:    isValidFormat0
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_emmef_sndfile_SoundFileType_isValidFormat0
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_emmef_sndfile_SoundFileType
 * Method:    getSndFileVersion0
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_emmef_sndfile_SoundFileType_getSndFileVersion0
  (JNIEnv *, jclass);

/*
 * Class:     org_emmef_sndfile_SoundFileType
 * Method:    getMajorFormatCount0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_emmef_sndfile_SoundFileType_getMajorFormatCount0
  (JNIEnv *, jclass);

/*
 * Class:     org_emmef_sndfile_SoundFileType
 * Method:    getMajorFormatInfo0
 * Signature: (ILorg/emmef/sndfile/FormatInfo;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_emmef_sndfile_SoundFileType_getMajorFormatInfo0
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_emmef_sndfile_SoundFileType
 * Method:    getSubFormatCount0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_emmef_sndfile_SoundFileType_getSubFormatCount0
  (JNIEnv *, jclass);

/*
 * Class:     org_emmef_sndfile_SoundFileType
 * Method:    getSubFormatInfo0
 * Signature: (ILorg/emmef/sndfile/FormatInfo;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_emmef_sndfile_SoundFileType_getSubFormatInfo0
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_emmef_sndfile_SoundFileType
 * Method:    initLibSoundFile
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_emmef_sndfile_SoundFileType_initLibSoundFile
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
